config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auth/spotify/callback', to: 'spotify#create'
  get '/auth/facebook/callback', to: 'sessions#create'
  get '/dashboard', to: 'dashboard#show'
  delete '/logout', to: 'sessions#destroy'

  namespace :group do
    resources :playlists, only: [:new, :create, :show, :destroy]
    resources :invites, only: [:index, :update, :destroy]
  end

  namespace :personal do
    resources :playlists, only: [:new, :create, :show, :destroy]
  end

  namespace :api do
    namespace :v1 do

      namespace :personal do
        post 'platform_playlists', to: 'platform_playlists#create'
      end

      namespace :group do
        post 'platform_playlists', to: 'platform_playlists#create'
      end

    end
  end
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
  has_many :group_playlists
  has_many :groups, through: :group_playlists
  belongs_to :platform
  belongs_to :service_playlist
  validates :name, presence: true

  def name_params
    if self.name.length > 18
      self.name[0..15] + "..."
    else
      self.name[0..15]
    end
  end

  def platform_type
    self.platform.name
  end

  def genres
    [ "All", "Rap", "Country", "Hip-hop",
      "Jazz", "Alternative", "Rock", "Punk"].sort
  end

  def platform_create(user_auth)
    playlist = create_playlist_by_platform(user_auth).id
    self.update_attribute(:service_playlist_id, playlist)
  end

  def populate(user_auth, tracks)
    sanitized_songs = sanitize_songs(tracks)
    tracks = save_songs_by_platform(sanitized_songs, user_auth)
    save_songs_to_db(tracks)
  end

  def user_tracks_saved_by_platform(user_auth)
    platform = Platform.find(self.platform_id)
    case platform.name
    when "spotify"
      @spotify_service = SpotifyService.new
      saved_songs = @spotify_service.retrieve_saved(user_auth)
    end
    saved_songs
  end

  def retrieve_echonest_tracks(saved_songs)
    case platform.name
    when "spotify" then echo_tracks = EchonestService.find_by_spotify(saved_songs)
    end
    echo_tracks
  end

  def retrieve_playlist_from_likes(echo_tracks)
    EchonestService.retrieve_playlist_from_likes(echo_tracks)
  end

  def sanitize_songs(tracks)
    # songs.map do |song|
    #   song if !(self.songs.find_by(track_id: song))
    # end.compact
    tracks
  end

  def save_songs_by_platform(sanitized_songs, user_auth)
    platform = Platform.find(self.platform_id)
    case platform.name
    when "spotify"
      @spotify_service = SpotifyService.new
      tracks = @spotify_service.save_playlist(sanitized_songs, user_auth, self)
    end
    tracks
  end

  def save_songs_to_db(tracks)
    self.playlist_songs.destroy_all
    tracks.each do |song|
      artists = song.artists.map {|artist| artist.name}.join(', ')
      self.songs << Song.create(title: song.name,
                                track_id: song.id,
                                artist: artists,
                                platform_id: self.platform_id,
                                image: song.album.images[2]['url'],
                                album: song.album.name,
                                link: song.external_urls["spotify"])
    end
  end

  def create_playlist_by_platform(user_auth)
    platform = Platform.find(self.platform_id)
    case platform.name
    when "spotify"
      @spotify_service = SpotifyService.new
      @spotify_service.create_playlist(self.name, user_auth)
    end
  end

end

app/controllers/api/v1/personal/platform_playlists_controller.rb
class Api::V1::Personal::PlatformPlaylistsController < Api::ApiController

  respond_to :json, :js

  def create
    @playlist = Playlist.find(params[:id])
    current_user.create_personal_playlist(spotify_user, @playlist)

    respond_to do |format|
      format.js
    end
  end

end

app/controllers/group/playlists_controller.rb
class Group::PlaylistsController < ApplicationController

  def new
    @playlist = Playlist.new
    @friends = facebook_user.get_connections('me', 'friends')
  end

  def show
    @playlist = playlist_owner?
    @users = @playlist.groups.first.users
  end

  def create
    @playlist = Playlist.new(playlist_params(params))
    create_group_redirect(params)
  end

  def destroy
    playlist = Playlist.find(params[:id])

    delete_group_redirect(playlist)
  end

  private

  def delete_group_redirect(playlist)
    playlist.group_playlists.destroy_all
    playlist.playlist_songs.destroy_all
    playlist.destroy
    redirect_to dashboard_path
  end

  def create_group_redirect(params)
    if @playlist.save
      group = Group.create
      group.create_group(current_user, params, @playlist)
      redirect_to group_playlist_path(@playlist.id)
    else
      @friends = facebook_user.get_connections('me', 'friends')
      render :new
    end
  end

  def playlist_params(params)
    playlist_params = params.require(:post).permit( :name,
                                      :description,
                                      :platform_id)

    playlist_params[:preferences] = {genre: params[:post][:genre], type: 'group'}
    playlist_params
  end

  def group_users_params
    params.permit(:fb_ids)
  end

end

app/controllers/personal/playlists_controller.rb
class Personal::PlaylistsController < ApplicationController

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params(params))

    create_redirect
  end

  def show
    @playlist = playlist_owner?
  end

  def destroy
    playlist = Playlist.find(params['id'])

    delete_redirect(playlist)
  end

  private

  def playlist_params(params)
    playlist_params = params.require(:post).permit(:name,
                                      :description,
                                      :platform_id)

    playlist_params[:preferences] = {genre: params[:post][:genre], type: 'personal'}
    playlist_params
  end

  def create_redirect
    if @playlist.save
      current_user.playlists << @playlist
      redirect_to personal_playlist_path(@playlist.id)
    else
      render :new
    end
  end

  def delete_redirect(playlist)
    playlist.playlist_songs.delete_all
    playlist.destroy

    redirect_to dashboard_path
  end
end

app/views/personal/playlists/_songs.html.erb
<table class="table table-hover">
  <tr>
    <th>#</th>
    <th></th>
    <th>Song Title</th>
    <th>Artist</th>
    <th>Album</th>
    <th></th>
  </tr>
  <% count = 0 %>

  <% cache cache_key_for(Playlist, "#{@playlist.id}") do %>
    <% playlist.songs.each do |song| %>
    <% count += 1 %>
    <tr>
      <td><%= count %></td>
      <td><%= image_tag song.image, class:"img-circle" %></td>
      <td><%= song.truncate('title') %></td>
      <td><%= song.truncate('artist') %></td>
      <td><%= song.truncate('album') %></td>
      <td>
        <a href="<%= song.link %>" class="provider"><%= image_tag 'spotify_button' %></a>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/personal/playlists/new.html.erb
  <div class="container centered" style="width:40%">
  <h1>Create Personal Playlist</h1>
  <%= simple_form_for :post, url: personal_playlists_path, method: :post do |f| %>

    <%= render partial: "/shared/errors", locals: {target: @playlist} %>

    <div class="form-group">
    <h2 class="form-text">name:</h2>
    <%= f.text_field :name, class: "form-control", id: "personal_name"%>
    <br>
    </div>

    <div class="form-group">
    <h2 class="form-text">description:</h2>
    <%= f.text_field :description, class: "form-control", id: "personal_description" %>
    <br>
    </div>

    <div class="form-group">
    <h2 class="form-text">service:</h2>
    <%= f.collection_select :platform_id, Platform.all, :id, :name, class:"form-form"  %>
    <br>
    </div>

    <div class="form-group">
    <h2 class="form-text">genre:</h2>
    <%= f.select(:genre, @playlist.genres, {}, { :class => 'form-control' }) %>
    <br>
    </div>

    <div class="form-group">
    <%= f.submit "Create Playlist", class:"btn btn-primary btn-lg active logout-button" %>
    </div>
  <% end %>
</div>

app/views/personal/playlists/show.html.erb
<div class="fluid-container">
  <div class="panel">
    <%= render partial: "/layouts/logout_button" %>
    <!-- Default panel contents -->
    <div class="panel-heading" style="font-family:'Telex',sans-serif;"><%= @playlist.name %>
      <h4><%= @playlist.description %></h4>
    </div>
    <div class="panel-body">
      <%= link_to "Remove Playlist", personal_playlist_path(@playlist), method: :delete, :data => { :confirm => "This will prevent this playlist from being updated! This will not remove the playlist from your service."}, class:"btn btn-primary btn-lg blue-button remove" %>
    </div>

    <!-- Table -->
    <% if @playlist.songs.empty? %>
      <div class="playlistId" id="<%= @playlist.id %>">
      </div>
    <% end %>
    <% if @playlist.songs.empty? %>
      <div id="personalSongs">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="container center" style="text-color:white;">
              <h1> fresh tracks coming your way, hang tight! </h1>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <table class="table table-hover">
        <tr>
          <th>#</th>
          <th></th>
          <th>Song Title</th>
          <th>Artist</th>
          <th>Album</th>
          <th></th>
        </tr>
        <% count = 0 %>
        <% cache cache_key_for(Playlist, "#{@playlist.id}") do %>
          <% @playlist.songs.last(30).each do |song| %>
          <% count += 1 %>
          <tr>
            <td><%= count %></td>
            <td><%= image_tag song.image, class:"img-circle" %></td>
            <td><%= song.truncate('title') %></td>
            <td><%= song.truncate('artist') %></td>
            <td><%= song.truncate('album') %></td>
            <td>
              <a href="<%= song.link %>" class="provider"><%= image_tag 'spotify_button' %></a>
            </td>
          </tr>
          <% end %>
        <% end %>
      <% end %>
    </table>
  </div>
</div>