config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auth/spotify/callback', to: 'spotify#create'
  get '/auth/facebook/callback', to: 'sessions#create'
  get '/dashboard', to: 'dashboard#show'
  delete '/logout', to: 'sessions#destroy'

  namespace :group do
    resources :playlists, only: [:new, :create, :show, :destroy]
    resources :invites, only: [:index, :update, :destroy]
  end

  namespace :personal do
    resources :playlists, only: [:new, :create, :show, :destroy]
  end

  namespace :api do
    namespace :v1 do

      namespace :personal do
        post 'platform_playlists', to: 'platform_playlists#create'
      end

      namespace :group do
        post 'platform_playlists', to: 'platform_playlists#create'
      end

    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_users
  has_many :users, through: :group_users
  has_many :group_playlists
  has_many :playlists, through: :group_playlists
  has_many :invites

  def self.create_group_playlist(playlist, spotify_user)
    group = playlist.groups[0]
    playlist.platform_create(spotify_user)
    saved_songs = group.grab_liked_songs
    group.group_populate(saved_songs)
  end

  def create_group(user, params, playlist)
    Invite.send_invite(params['fb_ids'], self)
    self.users << user
    self.playlists << playlist
    user.playlists << playlist
  end

  def update_group(invite, user)
    playlist_clone = self.playlists.first
    playlist = Playlist.create(name: playlist_clone.name,
                               description: playlist_clone.description,
                               preferences: playlist_clone.preferences,
                               platform_id: playlist_clone.platform_id)
    user.playlists << playlist
    self.users << user
    self.playlists << playlist
    invite.destroy
    playlist
  end

  def grab_liked_songs
    saved_songs = self.users.map do |user|
      platform = self.playlists.first.platform
      user_auth = user.find_token(platform).auth
      spotify_user = RSpotify::User.new(JSON.parse(user_auth))
      SpotifyService.new.retrieve_saved(spotify_user)
    end
    saved_songs
  end

  def group_populate(saved_songs)
    self.users.each do |user|
      platform = self.playlists.first.platform
      playlist = self.playlists.find_by(user_id: user.id)
      user_auth = user.find_token(platform).auth
      spotify_user = RSpotify::User.new(JSON.parse(user_auth))
      playlist.populate(spotify_user, saved_songs)
    end
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
  has_many :group_playlists
  has_many :groups, through: :group_playlists
  belongs_to :platform
  belongs_to :service_playlist
  validates :name, presence: true

  def name_params
    if self.name.length > 18
      self.name[0..15] + "..."
    else
      self.name[0..15]
    end
  end

  def platform_type
    self.platform.name
  end

  def genres
    [ "All", "Rap", "Country", "Hip-hop",
      "Jazz", "Alternative", "Rock", "Punk"].sort
  end

  def platform_create(user_auth)
    playlist = create_playlist_by_platform(user_auth).id
    self.update_attribute(:service_playlist_id, playlist)
  end

  def populate(user_auth, tracks)
    sanitized_songs = sanitize_songs(tracks)
    tracks = save_songs_by_platform(sanitized_songs, user_auth)
    save_songs_to_db(tracks)
  end

  def user_tracks_saved_by_platform(user_auth)
    platform = Platform.find(self.platform_id)
    case platform.name
    when "spotify"
      @spotify_service = SpotifyService.new
      saved_songs = @spotify_service.retrieve_saved(user_auth)
    end
    saved_songs
  end

  def retrieve_echonest_tracks(saved_songs)
    case platform.name
    when "spotify" then echo_tracks = EchonestService.find_by_spotify(saved_songs)
    end
    echo_tracks
  end

  def retrieve_playlist_from_likes(echo_tracks)
    EchonestService.retrieve_playlist_from_likes(echo_tracks)
  end

  def sanitize_songs(tracks)
    # songs.map do |song|
    #   song if !(self.songs.find_by(track_id: song))
    # end.compact
    tracks
  end

  def save_songs_by_platform(sanitized_songs, user_auth)
    platform = Platform.find(self.platform_id)
    case platform.name
    when "spotify"
      @spotify_service = SpotifyService.new
      tracks = @spotify_service.save_playlist(sanitized_songs, user_auth, self)
    end
    tracks
  end

  def save_songs_to_db(tracks)
    self.playlist_songs.destroy_all
    tracks.each do |song|
      artists = song.artists.map {|artist| artist.name}.join(', ')
      self.songs << Song.create(title: song.name,
                                track_id: song.id,
                                artist: artists,
                                platform_id: self.platform_id,
                                image: song.album.images[2]['url'],
                                album: song.album.name,
                                link: song.external_urls["spotify"])
    end
  end

  def create_playlist_by_platform(user_auth)
    platform = Platform.find(self.platform_id)
    case platform.name
    when "spotify"
      @spotify_service = SpotifyService.new
      @spotify_service.create_playlist(self.name, user_auth)
    end
  end

end

app/controllers/api/v1/group/platform_playlists_controller.rb
class Api::V1::Group::PlatformPlaylistsController < Api::ApiController

  respond_to :json, :js

  def create
    @playlist = Playlist.find(params[:id])
    Group.create_group_playlist(@playlist, spotify_user)

    respond_to do |format|
      format.js
    end
  end

end

app/controllers/group/invites_controller.rb
class Group::InvitesController < ApplicationController

  def index
    @invites = current_user.invites
  end

  def update
    invite = Invite.find(params[:id])
    group = invite.group
    playlist = group.update_group(invite, current_user)

    redirect_to group_playlist_path(playlist.id)
  end

  def destroy
    invite = Invite.find(params[:id])
    invite.destroy
    redirect_to dashboard_path
  end

end

app/controllers/group/playlists_controller.rb
class Group::PlaylistsController < ApplicationController

  def new
    @playlist = Playlist.new
    @friends = facebook_user.get_connections('me', 'friends')
  end

  def show
    @playlist = playlist_owner?
    @users = @playlist.groups.first.users
  end

  def create
    @playlist = Playlist.new(playlist_params(params))
    create_group_redirect(params)
  end

  def destroy
    playlist = Playlist.find(params[:id])

    delete_group_redirect(playlist)
  end

  private

  def delete_group_redirect(playlist)
    playlist.group_playlists.destroy_all
    playlist.playlist_songs.destroy_all
    playlist.destroy
    redirect_to dashboard_path
  end

  def create_group_redirect(params)
    if @playlist.save
      group = Group.create
      group.create_group(current_user, params, @playlist)
      redirect_to group_playlist_path(@playlist.id)
    else
      @friends = facebook_user.get_connections('me', 'friends')
      render :new
    end
  end

  def playlist_params(params)
    playlist_params = params.require(:post).permit( :name,
                                      :description,
                                      :platform_id)

    playlist_params[:preferences] = {genre: params[:post][:genre], type: 'group'}
    playlist_params
  end

  def group_users_params
    params.permit(:fb_ids)
  end

end

app/controllers/personal/playlists_controller.rb
class Personal::PlaylistsController < ApplicationController

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params(params))

    create_redirect
  end

  def show
    @playlist = playlist_owner?
  end

  def destroy
    playlist = Playlist.find(params['id'])

    delete_redirect(playlist)
  end

  private

  def playlist_params(params)
    playlist_params = params.require(:post).permit(:name,
                                      :description,
                                      :platform_id)

    playlist_params[:preferences] = {genre: params[:post][:genre], type: 'personal'}
    playlist_params
  end

  def create_redirect
    if @playlist.save
      current_user.playlists << @playlist
      redirect_to personal_playlist_path(@playlist.id)
    else
      render :new
    end
  end

  def delete_redirect(playlist)
    playlist.playlist_songs.delete_all
    playlist.destroy

    redirect_to dashboard_path
  end
end

app/views/group/playlists/_songs.html.erb
<table class="table table-hover">
  <tr>
    <th>#</th>
    <th></th>
    <th>Song Title</th>
    <th>Artist</th>
    <th>Album</th>
    <th></th>
  </tr>
  <% count = 0 %>

  <% cache cache_key_for(Playlist, "#{@playlist.id}") do %>
    <% playlist.songs.each do |song| %>
    <% count += 1 %>
    <tr>
      <td><%= count %></td>
      <td><%= image_tag song.image, class:"img-circle" %></td>
      <td><%= song.truncate('title') %></td>
      <td><%= song.truncate('artist') %></td>
      <td><%= song.truncate('album') %></td>
      <td>
        <a href="<%= song.link %>" class="provider"><%= image_tag 'spotify_button' %></a>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/group/playlists/new.html.erb
<div class="container centered" style="width:40%">
  <h1>Create Group Playlist</h1>
  <%= simple_form_for :post, url: group_playlists_path, method: :post do |f| %>

    <%= render partial: "/shared/errors", locals: {target: @playlist} %>

    <div class="form-group">
      <h2> <%= f.label :name, "name:"%></h2>
      <%= f.text_field :name, class: "form-control"%>
      <br>
    </div>

    <div class="form-group">
      <h2><%= f.label :description, "description:"%></h2>
      <%= f.text_field :description, class: "form-control" %>
      <br>
    </div>

    <div class="form-group">
      <h2 class="form-text">service:</h2>
      <span class:"something"><%= f.collection_select :platform_id, Platform.all, :id, :name %></span>
      <br>
    </div>

    <div class="form-group">
      <h2 class="form-text">genre:</h2>
      <%= f.select(:genre, @playlist.genres, {}, { :class => 'form-control' }) %>
      <br>
    </div>

    <div class="form-group">
      <div class="checkbox">
        <% @friends.each do |friend| %>
        <%= check_box_tag 'fb_ids', friend['id'], false, id:"#{friend['name'].split[1]}" %>
        <%= f.label friend['name'] %> <br>
        <% end %>
      </div>
      <br>
    </div>

    <div class="form-group">
      <%= f.submit "Create Playlist", class:"btn btn-primary btn-lg active logout-button" %>
    </div>
  <% end %>
</div>

app/views/group/playlists/show.html.erb
<div class="fluid-container">
  <div class="panel">
    <%= render partial: "/layouts/logout_button" %>

    <!-- Default panel contents -->
    <div class="panel-heading"><%= @playlist.name %>
    <h4><%= @playlist.description %></h4>
    </div>
    <div class="panel-body">
      <span><%= link_to "Remove Playlist", group_playlist_path(@playlist),
      method: :delete,
      :data => { :confirm => "This will prevent this playlist from being updated! This will not remove the playlist from your service."},
      class:"btn btn-primary btn-lg blue-button remove" %></span>

      <span class="friends">
        <% @users.each do |user| %>
        <%= image_tag user.image, class:"fb_image", title: user.name %>
        <% end %>
      </span>
    </div>

    <!-- Table -->
    <% if @playlist.songs.empty? %>
      <div class="playlistId" id="<%= @playlist.id %>">
      </div>
    <% end %>
    <% if @playlist.songs.empty? %>
      <div id="groupSongs">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="container center" style="text-color:white;">
              <h1> fresh tracks coming your way, hang tight! </h1>
            </div>
          </div>
        </div>
      </div>
    <% else %>
    <table class="table table-hover">
      <tr>
        <th>#</th>
        <th></th>
        <th>Song Title</th>
        <th>Artist</th>
        <th>Album</th>
        <th></th>
      </tr>
      <% count = 0 %>
        <% cache cache_key_for(Playlist, "#{@playlist.id}") do %>
          <% @playlist.songs.last(30).each do |song| %>
            <% count += 1 %>
            <tr>
              <td><%= count %></td>
              <td><%= image_tag song.image, class:"img-circle" %></td>
              <td><%= song.title %></td>
              <td><%= song.artist %></td>
              <td><%= song.album %></td>
              <td><a href="#{link}" class="provider"><%= image_tag 'spotify_button' %></a></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </table>
  </div>
</div>