config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auth/spotify/callback', to: 'spotify#create'
  get '/auth/facebook/callback', to: 'sessions#create'
  get '/dashboard', to: 'dashboard#show'
  delete '/logout', to: 'sessions#destroy'

  namespace :group do
    resources :playlists, only: [:new, :create, :show, :destroy]
    resources :invites, only: [:index, :update, :destroy]
  end

  namespace :personal do
    resources :playlists, only: [:new, :create, :show, :destroy]
  end

  namespace :api do
    namespace :v1 do

      namespace :personal do
        post 'platform_playlists', to: 'platform_playlists#create'
      end

      namespace :group do
        post 'platform_playlists', to: 'platform_playlists#create'
      end

    end
  end
end

app/views/layouts/_logout_button.html.erb
<div class="user-dash-info">
  <button type="button" class="btn btn-primary btn-lg active blue-button">
    <%= image_tag current_user.image, class: "img-circle user-img" %>

    <%= link_to 'Logout', logout_path, method: :delete, class:"logout", role:'button' %>
  </button>
</div>

app/views/layouts/_navbar.html.erb
<div class="nav_top">
  <ul class='nav navbar-inverse nav-pills nav-stacked nav_style'>
    <li role="presentation" class="active"><h1><a style="font-family:Pacifico;font-size:70px;" href='/dashboard'>Tango</a></h1></li>
    <li role="presentation"><h3><%= current_user.name %></h3></li>
    <li role="presentation"><h4>My Playlist<a href='/personal/playlists/new' ><span class="glyphicon glyphicon-plus-sign" id="add_playlist"></span></a></h4></li>
    <br>
    <% current_user.user_playlists.each do |playlist| %>
      <li class="<%= playlist.platform_type  %>" role="presentation"><%= link_to playlist.name_params, personal_playlist_path(playlist) %></li>
    <% end %>

    <li role="presentation"><h4>My Groups<a href='/group/playlists/new'><span class="glyphicon glyphicon-plus-sign" id="add_group"></span></a></h4></li>

    <% current_user.group_playlists.each do |playlist| %>
      <li class="<%= playlist.platform_type %>"role="presentation"><%= link_to playlist.name_params, group_playlist_path(playlist) %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tango</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Telex' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Pacifico|Raleway:500' rel='stylesheet' type='text/css'>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="fluid-container backdrop">
  <div class='row'>
    <% if current_user %>
      <div class='col-md-2'>
        <%= render partial: '/layouts/navbar' %>
      </div>
        <div class ='col-md-10 main-panel'>

      <% else %>
        <div class ='col-md-12 main-panel'>
    <% end %>
      <%= yield %>
    </div>
  </div>
</div>


</body>
</html>